{% set name = "spleeter-gpu" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: ee7c797a7bf7a957f6175012bdacc0a3eb0052b1ac7d2857aba16dde6a8d36fd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - spleeter = spleeter.__main__:entrypoint

requirements:
  host:
    - python >=3.6,<3.8
    - pip
  run:
    - python >=3.6,<3.8
    - requests
    - setuptools
    - importlib_resources
    - tensorflow-gpu ==1.14.0
    - pandas ==0.25.1
    - ffmpeg-python
    - norbert

test:
  imports:
    - spleeter

about:
  home: https://github.com/deezer/spleeter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Deezer source separation library with pretrained models based on tensorflow.
  doc_url: https://github.com/deezer/spleeter/wiki
  dev_url: https://github.com/deezer/spleeter

extra:
  recipe-maintainers:
    - Faylixe
    - romi1502
